'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17626
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System.Runtime.Serialization
	Imports System
Namespace ClientApp.ReportServiceReference


	<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name:="ReportParameterInfo", Namespace:="http://schemas.datacontract.org/2004/07/HostApp"), System.SerializableAttribute(), System.Runtime.Serialization.KnownTypeAttribute(GetType(String())), System.Runtime.Serialization.KnownTypeAttribute(GetType(ClientApp.ReportServiceReference.ReportParameterInfo()))> _
	Partial Public Class ReportParameterInfo
		Inherits Object
		Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged

		<System.NonSerializedAttribute()> _
		Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

		<System.Runtime.Serialization.OptionalFieldAttribute()> _
		Private NameField As String

		<System.Runtime.Serialization.OptionalFieldAttribute()> _
		Private ValueField As Object

		<Global.System.ComponentModel.BrowsableAttribute(False)> _
		Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
			Get
				Return Me.extensionDataField
			End Get
			Set(ByVal value As System.Runtime.Serialization.ExtensionDataObject)
				Me.extensionDataField = value
			End Set
		End Property

		<System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Name() As String
			Get
				Return Me.NameField
			End Get
			Set(ByVal value As String)
				If (Object.ReferenceEquals(Me.NameField, value) <> True) Then
					Me.NameField = value
					Me.RaisePropertyChanged("Name")
				End If
			End Set
		End Property

		<System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Value() As Object
			Get
				Return Me.ValueField
			End Get
			Set(ByVal value As Object)
				If (Object.ReferenceEquals(Me.ValueField, value) <> True) Then
					Me.ValueField = value
					Me.RaisePropertyChanged("Value")
				End If
			End Set
		End Property

		Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

		Protected Sub RaisePropertyChanged(ByVal propertyName As String)
			Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
			If (PropertyChangedEvent IsNot Nothing) Then
				PropertyChangedEvent(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class

	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ReportServiceReference.IReportService")> _
	Public Interface IReportService

		<System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportService/GetReportNames", ReplyAction:="http://tempuri.org/IReportService/GetReportNamesResponse")> _
		Function GetReportNames() As String()

		<System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportService/GetReportLayout", ReplyAction:="http://tempuri.org/IReportService/GetReportLayoutResponse")> _
		Function GetReportLayout(ByVal reportName As String) As Byte()

		<System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportService/GetReportDocument", ReplyAction:="http://tempuri.org/IReportService/GetReportDocumentResponse")> _
		Function GetReportDocument(ByVal reportName As String) As Byte()

		<System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IReportService/GetParametrizedReportDocument", ReplyAction:="http://tempuri.org/IReportService/GetParametrizedReportDocumentResponse")> _
		Function GetParametrizedReportDocument(ByVal reportName As String, ByVal parameters() As ClientApp.ReportServiceReference.ReportParameterInfo) As Byte()
	End Interface

	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
	Public Interface IReportServiceChannel
	Inherits ClientApp.ReportServiceReference.IReportService, System.ServiceModel.IClientChannel
	End Interface

	<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
	Partial Public Class ReportServiceClient
		Inherits System.ServiceModel.ClientBase(Of ClientApp.ReportServiceReference.IReportService)
		Implements ClientApp.ReportServiceReference.IReportService

		Public Sub New()
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String)
			MyBase.New(endpointConfigurationName)
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
			MyBase.New(endpointConfigurationName, remoteAddress)
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
			MyBase.New(endpointConfigurationName, remoteAddress)
		End Sub

		Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
			MyBase.New(binding, remoteAddress)
		End Sub

		Public Function GetReportNames() As String() Implements ClientApp.ReportServiceReference.IReportService.GetReportNames
			Return MyBase.Channel.GetReportNames()
		End Function

		Public Function GetReportLayout(ByVal reportName As String) As Byte() Implements ClientApp.ReportServiceReference.IReportService.GetReportLayout
			Return MyBase.Channel.GetReportLayout(reportName)
		End Function

		Public Function GetReportDocument(ByVal reportName As String) As Byte() Implements ClientApp.ReportServiceReference.IReportService.GetReportDocument
			Return MyBase.Channel.GetReportDocument(reportName)
		End Function

		Public Function GetParametrizedReportDocument(ByVal reportName As String, ByVal parameters() As ClientApp.ReportServiceReference.ReportParameterInfo) As Byte() Implements ClientApp.ReportServiceReference.IReportService.GetParametrizedReportDocument
			Return MyBase.Channel.GetParametrizedReportDocument(reportName, parameters)
		End Function
	End Class
End Namespace
